services:
  database:
    image: postgres:16.3
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -U postgres" ] # todo: check how to make init-migrate-seed wait for this
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
#    cpu_count: 2
    networks:
      - backend-network

  init-migrate-seed:
    image: local/nhannguyenacademy/ecommerce:0.0.1
    pull_policy: never
    container_name: init-migrate-seed
    restart: unless-stopped
    entrypoint: ['./admin', 'migrate-seed']
    networks:
      - backend-network
    deploy:
      restart_policy:
        condition: none
    depends_on:
      - database

  ecommerce:
    image: local/nhannguyenacademy/ecommerce:0.0.1
    pull_policy: never
    container_name: ecommerce
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - GOMAXPROCS
      - GOGC=off
      - GOMEMLIMIT
#    healthcheck:
#      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/api/v1/liveness || exit 1"]
#      interval: 5s
#      timeout: 5s
#      retries: 2
#      start_period: 2s
    networks:
      - backend-network
    depends_on:
      - init-migrate-seed

networks:
  backend-network:
    driver: bridge
