services:
  database:
    image: postgres:16.3
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database-data:/var/lib/postgresql/data
#      - ./pg_hba.conf:/etc/pg_hba.conf # https://github.com/ardanlabs/service/pull/285
#    command: [ '-c', 'hba_file=/etc/pg_hba.conf' ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    cpu_count: 2
    networks:
      ecommerce-system-network:
        ipv4_address: 10.5.0.2

#  init-migrate-seed:
#    image: local/nhannguyenacademy/ecommerce:0.0.1
#    pull_policy: never
#    container_name: init-migrate-seed
#    restart: unless-stopped
#    entrypoint: ['./admin', 'migrate-seed']
#    environment:
#      - ECOMMERCE_DB_USER=postgres
#      - ECOMMERCE_DB_PASSWORD=postgres
#      - ECOMMERCE_DB_HOST=database
#      - ECOMMERCE_DB_DISABLE_TLS=true
#    networks:
#      ecommerce-system-network:
#        ipv4_address: 10.5.0.10
#    deploy:
#      restart_policy:
#        condition: none
#    depends_on:
#      - database

#  ecommerce:
#    image: local/nhannguyenacademy/ecommerce:0.0.1
#    pull_policy: never
#    container_name: ecommerce
#    restart: unless-stopped
#    ports:
#      - "3000:3000"
#      - "3010:3010"
#    environment:
#      - GOMAXPROCS
#      - GOGC=off
#      - GOMEMLIMIT
#      - ECOMMERCE_DB_USER=postgres
#      - ECOMMERCE_DB_PASSWORD=postgres
#      - ECOMMERCE_DB_HOST=database
#      - ECOMMERCE_DB_DISABLE_TLS=true
#      - ECOMMERCE_AUTH_HOST=http://auth:6000
#      - KUBERNETES_NAMESPACE
#      - KUBERNETES_NAME
#      - KUBERNETES_POD_IP
#      - KUBERNETES_NODE_NAME
#    healthcheck:
#      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/v1/liveness || exit 1"]
#      interval: 5s
#      timeout: 5s
#      retries: 2
#      start_period: 2s
#    networks:
#      ecommerce-system-network:
#        ipv4_address: 10.5.0.15
#    depends_on:
#      - init-migrate-seed

#  metrics:
#    image: localhost/nhanguyenacademy/metrics:0.0.1
#    pull_policy: never
#    container_name: metrics
#    restart: unless-stopped
#    ports:
#      - "4000:4000"
#      - "4010:4010"
#      - "4020:4020"
#    cpus: 1
#    environment:
#      - GOMAXPROCS=1
#      - METRICS_COLLECT_FROM=http://ecommerce:3010/debug/vars
#    networks:
#      ecommerce-system-network:
#        ipv4_address: 10.5.0.20
#    depends_on:
#      - ecommerce

volumes:
  database: {}

networks:
  ecommerce-system-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24
